# Generated by Django 3.2 on 2023-01-10 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_posting'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='posting',
            table='Posting',
        ),
    ]
