# Generated by Django 3.2 on 2023-01-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_alter_posting_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
