# Generated by Django 3.2 on 2023-01-12 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reality', '0001_initial'),
        ('community', '0007_posting_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posting',
            name='reality',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='reality.reality'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posting',
            name='upload_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Prefer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.IntegerField(default=0)),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.posting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.IntegerField(default=0)),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.posting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
