# Generated by Django 3.2 on 2023-01-12 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_auto_20230112_1954'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookmark',
            table='Bookmark',
        ),
        migrations.AlterModelTable(
            name='prefer',
            table='Prefer',
        ),
    ]
