# Generated by Django 3.2 on 2023-01-16 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_auto_20230116_1646'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hate',
            table='Hate',
        ),
        migrations.AlterModelTable(
            name='like',
            table='Likes',
        ),
    ]
