# Generated by Django 3.2 on 2023-01-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_auto_20230116_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='prefer',
        ),
        migrations.AddField(
            model_name='prefer',
            name='preference',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Hate',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
