# Generated by Django 3.2 on 2023-01-17 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentPrefer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'CommentPrefer',
            },
        ),
        migrations.CreateModel(
            name='PostingPrefer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.IntegerField(null=True)),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_prefers', to='community.posting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_prefers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PostingPrefer',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='upload_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Prefer',
        ),
        migrations.AddField(
            model_name='commentprefer',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_prefers', to='community.comment'),
        ),
        migrations.AddField(
            model_name='commentprefer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_prefers', to=settings.AUTH_USER_MODEL),
        ),
    ]
