# Generated by Django 3.2 on 2023-01-24 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0014_auto_20230117_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentprefer',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefers', to='community.comment'),
        ),
        migrations.AlterField(
            model_name='postingprefer',
            name='posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefers', to='community.posting'),
        ),
    ]
