# Generated by Django 3.2 on 2023-01-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0015_auto_20230124_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
