# Generated by Django 3.2 on 2023-02-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0018_remove_user_email_remove_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.TextField(default='default_profile.jpg'),
        ),
    ]
