# Generated by Django 3.2 on 2023-01-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128, null=True)),
                ('first_name', models.CharField(max_length=128, null=True)),
                ('second_name', models.CharField(max_length=128, null=True)),
            ],
            options={
                'db_table': 'Reality',
            },
        ),
    ]
