# Generated by Django 3.2 on 2023-01-16 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reality', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reality',
            name='address',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.IntegerField(default=0)),
                ('reality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reality.reality')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Bookmark',
            },
        ),
    ]
