# Generated by Django 3.2 on 2023-01-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reality', '0002_auto_20230116_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reality',
            name='address',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
