# Generated by Django 3.2 on 2023-01-17 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reality', '0003_alter_reality_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='preference',
        ),
    ]
