# Generated by Django 3.2 on 2023-01-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reality', '0005_auto_20230117_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='reality',
            name='kapt_code',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reality',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
