# Generated by Django 3.2 on 2023-01-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reality', '0006_auto_20230124_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reality',
            name='x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='reality',
            name='y',
            field=models.FloatField(default=0.0),
        ),
    ]
