# Generated by Django 3.2 on 2023-01-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reality', '0007_auto_20230125_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='reality',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
