# Generated by Django 3.2 on 2023-02-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reality', '0008_reality_hits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reality',
            old_name='kapt_code',
            new_name='kaptCode',
        ),
        migrations.RemoveField(
            model_name='reality',
            name='address',
        ),
        migrations.RemoveField(
            model_name='reality',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='reality',
            name='second_name',
        ),
        migrations.AddField(
            model_name='reality',
            name='bjdCode',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='codeAptNm',
            field=models.CharField(max_length=51, null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='codeGarbage',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='codeHallNm',
            field=models.CharField(max_length=51, null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='codeHeatNm',
            field=models.CharField(max_length=51, null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='codeMgrNm',
            field=models.CharField(max_length=51, null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='codeNet',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='codeSaleNm',
            field=models.CharField(max_length=51, null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='codeStr',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='convenientFacility',
            field=models.CharField(max_length=501, null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='doroJuso',
            field=models.CharField(max_length=366, null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='educationFacility',
            field=models.CharField(max_length=501, null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='hoCnt',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='kaptAcompany',
            field=models.CharField(max_length=101, null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='kaptAddr',
            field=models.CharField(max_length=201, null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='kaptBcompany',
            field=models.CharField(max_length=101, null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='kaptDongCnt',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='kaptFax',
            field=models.CharField(max_length=21, null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='kaptMarea',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='reality',
            name='kaptMparea_135',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='kaptMparea_136',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='kaptMparea_60',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='kaptMparea_85',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='kaptName',
            field=models.CharField(max_length=51, null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='kaptTarea',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='reality',
            name='kaptTel',
            field=models.CharField(max_length=21, null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='kaptUrl',
            field=models.CharField(max_length=101, null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='kaptUsedate',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='kaptdCccnt',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='kaptdEcnt',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='kaptdPcnt',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='kaptdPcntu',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='kaptdWtimebus',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='kaptdWtimesub',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='kaptdaCnt',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='privArea',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='reality',
            name='subwayLine',
            field=models.CharField(max_length=51, null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='subwayStation',
            field=models.CharField(max_length=51, null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='welfareFacility',
            field=models.CharField(max_length=201, null=True),
        ),
    ]
