# Generated by Django 3.2 on 2023-02-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reality', '0009_auto_20230203_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='reality',
            name='bun',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='ji',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
