# Generated by Django 3.2 on 2023-02-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reality', '0010_auto_20230203_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='reality',
            name='archArea',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='reality',
            name='bcRat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='reality',
            name='emgenUseElvtCnt',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='engrGrade',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='etcStrct',
            field=models.CharField(max_length=501, null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='grndFlrCnt',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='heit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='reality',
            name='hhldCnt',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='mgmBldrgstPk',
            field=models.CharField(max_length=34, null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='platArea',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='reality',
            name='rideUseElvtCnt',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='rserthqkDsgnApplyYn',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='strctCd',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='strctCdNm',
            field=models.CharField(max_length=101, null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='totArea',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='reality',
            name='ugrndFlrCnt',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='vlRat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='reality',
            name='vlRatEstmTotArea',
            field=models.FloatField(default=0.0),
        ),
    ]
