# Generated by Django 3.2 on 2023-02-04 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reality', '0011_auto_20230203_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reality',
            name='emgenUseElvtCnt',
        ),
        migrations.RemoveField(
            model_name='reality',
            name='etcStrct',
        ),
        migrations.RemoveField(
            model_name='reality',
            name='grndFlrCnt',
        ),
        migrations.RemoveField(
            model_name='reality',
            name='heit',
        ),
        migrations.RemoveField(
            model_name='reality',
            name='rideUseElvtCnt',
        ),
        migrations.RemoveField(
            model_name='reality',
            name='rserthqkDsgnApplyYn',
        ),
        migrations.RemoveField(
            model_name='reality',
            name='strctCd',
        ),
        migrations.RemoveField(
            model_name='reality',
            name='strctCdNm',
        ),
        migrations.RemoveField(
            model_name='reality',
            name='ugrndFlrCnt',
        ),
    ]
