# Generated by Django 3.2 on 2023-02-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reality', '0014_linkerrtms_rtms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reality',
            name='kaptCode',
            field=models.CharField(db_index=True, max_length=16, null=True),
        ),
    ]
