# Generated by Django 3.2 on 2023-02-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reality', '0015_alter_reality_kaptcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkerrtms',
            name='kaptCode',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
