# Generated by Django 3.2 on 2023-02-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reality', '0017_rtms_serialnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkerrtms',
            name='RTMSkaptName',
        ),
        migrations.AddField(
            model_name='linkerrtms',
            name='bjd',
            field=models.CharField(db_index=True, default=None, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linkerrtms',
            name='bun',
            field=models.PositiveIntegerField(db_index=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linkerrtms',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linkerrtms',
            name='ji',
            field=models.PositiveIntegerField(db_index=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linkerrtms',
            name='sgg',
            field=models.CharField(db_index=True, default=None, max_length=5),
            preserve_default=False,
        ),
    ]
