# Generated by Django 3.2 on 2023-02-08 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reality', '0018_auto_20230208_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtms',
            name='serialNumber',
            field=models.CharField(max_length=41, null=True),
        ),
    ]
