# Generated by Django 3.2 on 2023-02-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reality', '0019_alter_rtms_serialnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkerrtms',
            old_name='bjd',
            new_name='bjdCode',
        ),
        migrations.RenameField(
            model_name='linkerrtms',
            old_name='sgg',
            new_name='sggCode',
        ),
        migrations.AddField(
            model_name='linkerrtms',
            name='bjdName',
            field=models.CharField(db_index=True, default=None, max_length=10),
            preserve_default=False,
        ),
    ]
