# Generated by Django 3.2 on 2023-02-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reality', '0020_auto_20230222_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkerrtms',
            name='bjdName',
            field=models.CharField(db_index=True, max_length=10, null=True),
        ),
    ]
