# Generated by Django 3.2 on 2023-02-22 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reality', '0021_alter_linkerrtms_bjdname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkerrtms',
            name='bjdName',
            field=models.CharField(db_index=True, default=None, max_length=10),
        ),
    ]
