# Generated by Django 3.2 on 2023-02-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reality', '0023_alter_linkerrtms_bjdname'),
    ]

    operations = [
        migrations.AddField(
            model_name='reality',
            name='amount',
            field=models.CharField(max_length=41, null=True),
        ),
        migrations.AddField(
            model_name='reality',
            name='useArea',
            field=models.FloatField(default=0.0),
        ),
    ]
