# Generated by Django 3.2 on 2023-03-06 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reality', '0024_auto_20230222_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='RTMSRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=41, null=True)),
                ('rent', models.CharField(max_length=16, null=True)),
                ('year', models.CharField(max_length=4, null=True)),
                ('month', models.CharField(max_length=2, null=True)),
                ('day', models.CharField(max_length=6, null=True)),
                ('useArea', models.FloatField(default=0.0)),
                ('jibun', models.CharField(max_length=11, null=True)),
                ('floor', models.CharField(max_length=4, null=True)),
                ('reality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RTMSRents', to='reality.reality')),
            ],
            options={
                'db_table': 'RTMSRent',
            },
        ),
    ]
