# Generated by Django 3.2 on 2023-03-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reality', '0026_remove_linkerrtms_bjdcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reality',
            name='kaptdPcnt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reality',
            name='kaptdPcntu',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
